sudo:  required
services: 
       - docker
before_install:
       - docker build -t seifbelhaj/docker-react12 -f Dockerfile.dev .
script:
       - docker run seifbelhaj/docker-react12 npm run test -- --coverage --watchAll=false
deploy:
  provider: azure_web_apps
  username: $AZURE_APP_SERVICE_USERNAME
  password: iiiiiiii
  site: $AZURE_APP_SERVICE_NAME
  on:
    branch: main
